### ISSUE TITLE
RPC port defaults to 6463, may not be the client with replugged

### ISSUE THREAD

**Issue by mugman174** [replugged-org/replugged-backend#2]
Many people may have multiple instances of Discord open, and the instance with Replugged may not be the first. The installer on the website (https://replugged.dev/install) connects port 6463, which corresponds to the first client opened, which may not be Replugged. The installer should instead check all the possible ports that could be used for RPC.

**Comment by mugman174** [comment]
@asportnoy

**Comment by asportnoy** [comment]
This can be fixed by running `rpcInstall` inside the loop before the break
